stages:
  - setup
  - test

install_mariadb:
  stage: setup
  script:
    - apt update
    - apt install mariadb-server -y
    - echo "12345678" | echo "n" | mysql_secure_installation
    - echo "12345678" | sudo mysql -u root -p
    - MariaDB [(none)]> CREATE DATABASE IF NOT EXISTS playlist;
  artifacts:
    paths:
      - /var/lib/mysql
  only:
    - ci-cd-yml-file-for-backend