services:
  backend:
    image: your_backend_image
    environment:
      DOCKER_ENV: true
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: database
      BACKEND: localhost
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/songs || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s

  database:
    image: mariadb:lts-jammy
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: playlist
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$MYSQL_ROOT_PASSWORD']
      interval: 10s
      retries: 5
      timeout: 5s

test_backend:
  stage: test
  image: gradle:jdk17
  script:
    - apt-get update
    - apt-get install -y curl
    - cd backend
    - curl -f http://backend:8080/api/songs
  only:
    - ci-cd-yml-file-for-backend