build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
  only:
    rules:
      - if: '$CI_COMMIT_BRANCH == "ci-cd-yml-file-for-frontend"'

test-job1:
  stage: test
  script:
    - echo "This job tests something"
  only:
    rules:
      - if: '$CI_COMMIT_BRANCH == "ci-cd-yml-file-for-frontend"'

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20
  only:
    rules:
      - if: '$CI_COMMIT_BRANCH == "ci-cd-yml-file-for-frontend"'

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
  only:
    rules:
      - if: '$CI_COMMIT_BRANCH == "ci-cd-yml-file-for-frontend"'
