default:
  image: ghcr.io/cirruslabs/flutter

before_script:
  - cd frontend

stages:
  - build_web
  - build_android

build_web_frontend:
  stage: build_web
  script:
    - flutter build web
  artifacts:
    paths:
      - build/web/
  only:
    - ci-cd-yml-file-for-frontend

build_android_app:
  stage: build_android
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
  only:
    - ci-cd-yml-file-for-frontend