.backend_settings: &backend_settings
  image: gradle:jdk17
  services:
    - name: mariadb:lts-jammy
      alias: mariadb
  variables:
    DATABASE_URL: jdbc:mariadb://mariadb:3306/playlist
    DATABASE_USERNAME: root
    DATABASE_PASSWORD: root_password
    DOCKER_ENV: true

.frontend_settings: &frontend_settings
  image: ghcr.io/cirruslabs/flutter
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - frontend/dotenv_dev
      - frontend/dotenv_prod

stages:
  - setup
  - frontend
  - backend
  - build_images
  - send_images

test_backend:
  stage: backend
  <<: *backend_settings
  script:
    - cd backend
    - gradle test
  artifacts:
    paths:
      - backend/build/reports/tests/
  only:
    - ci-cd-builds-docker-images

build_backend:
  stage: backend
  <<: *backend_settings
  script:
    - cd backend
    - gradle build
  artifacts:
    paths:
      - backend/build/libs/*.jar
  only:
    - ci-cd-builds-docker-images

setup_env_files:
  stage: setup
  <<: *frontend_settings
  script:
    - cd frontend
    - echo "SCHEME=$SCHEME" > dotenv_dev
    - echo "API_URL=$INSTANCE_IP" >> dotenv_dev
    - echo "SCHEME=$SCHEME" > dotenv_prod
    - echo "API_URL=$INSTANCE_IP" >> dotenv_prod
  only:
    - ci-cd-builds-docker-images

build_web_frontend_dev:
  stage: frontend
  <<: *frontend_settings
  script:
    - cd frontend
    - flutter pub run build_runner build
    - flutter build web -t lib/main_dev.dart
  artifacts:
    paths:
      - frontend/build/web
  only:
    - ci-cd-builds-docker-images

build_web_frontend_prod:
  stage: frontend
  <<: *frontend_settings
  script:
    - cd frontend
    - flutter pub run build_runner build
    - flutter build web -t lib/main_prod.dart
  artifacts:
    paths:
      - frontend/build/web
  only:
    - ci-cd-builds-docker-images

build_android_app_dev:
  stage: frontend
  <<: *frontend_settings
  script:
    - cd frontend
    - flutter pub run build_runner build
    - flutter build apk -t lib/main_dev.dart
  artifacts:
    paths:
      - frontend/build/app/outputs/flutter-apk
  only:
    - ci-cd-builds-docker-images

build_android_app_prod:
  stage: frontend
  <<: *frontend_settings
  script:
    - cd frontend
    - flutter pub run build_runner build
    - flutter build apk -t lib/main_prod.dart
  artifacts:
    paths:
      - frontend/build/app/outputs/flutter-apk
  only:
    - ci-cd-builds-docker-images

create_docker_images:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  stage: build_images
  script:
    - echo $LOGIN_PASSWORD | docker login -u $LOGIN_USERNAME --password-stdin registry.gitlab.com
    - docker-compose build
    - |
      images=$(docker images --format "{{.Repository}}:{{.Tag}}")

      for image in $images; do
        docker push "$image"
      done
  only:
    - ci-cd-builds-docker-images

send_image_to_database:
  stage: send_images
  image: ubuntu:latest
  script:
    - apt-get update && apt-get install -y openssh-client
    - base64 -d <<< "$AWS_SSH_KEY" > ssh_key.pem
    - chmod 400 ssh_key.pem
    - ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@$DATABASE_IP \
      "echo $LOGIN_PASSWORD | sudo docker login -u $LOGIN_USERNAME --password-stdin registry.gitlab.com &&
      sudo docker rm -f \$(sudo docker ps -aq) || true && sudo docker rmi -f \$(sudo docker images -aq) || true &&
      sudo docker pull registry.gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/database:latest &&
      sudo docker tag registry.gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/database:latest database &&
      sudo docker run -d --name database -p 3306:3306
      -e MYSQL_ROOT_PASSWORD=root_password
      -e MYSQL_USER=user
      -e MYSQL_PASSWORD=password
      -e MYSQL_DATABASE=playlist
      database"
  only:
    - separate-instance-database-used-by-ci-cd

send_images_to_backend:
  stage: send_images
  image: ubuntu:latest
  script:
    - apt-get update && apt-get install -y openssh-client
    - base64 -d <<< "$AWS_SSH_KEY" > ssh_key.pem
    - chmod 400 ssh_key.pem
    - ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@$IP_INSTANCE \
      "echo $LOGIN_PASSWORD | sudo docker login -u $LOGIN_USERNAME --password-stdin registry.gitlab.com &&
      sudo docker rm -f \$(sudo docker ps -aq) || true && sudo docker rmi -f \$(sudo docker images -aq) || true &&
      sudo docker pull registry.gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/backend:latest &&
      sudo docker tag registry.gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/backend:latest backend &&
      sudo docker run -d --name backend -p 8080:8080 
      -e DB_USER=user
      -e DB_PASSWORD=password
      -e DB_HOST=$DATABASE_IP
      backend"
  needs:
    - job: send_image_to_database
      artifacts: true
  only:
    - separate-instance-database-used-by-ci-cd
