.backend_settings: &backend_settings
  image: gradle:jdk17
  services:
    - name: mariadb:lts-jammy
      alias: mariadb
  variables:
    DATABASE_URL: jdbc:mariadb://mariadb:3306/playlist
    DATABASE_USERNAME: root
    DATABASE_PASSWORD: root_password
    DOCKER_ENV: true

.frontend_settings: &frontend_settings
  image: ghcr.io/cirruslabs/flutter
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - frontend/dotenv_dev
      - frontend/dotenv_prod

stages:
  - frontend
  - backend

test_backend:
  stage: backend
  <<: *backend_settings
  script:
    - cd backend
    - gradle test
  artifacts:
    paths:
      - backend/build/reports/tests/
  only:
    - ci-cd-yml-file-for-backend

build_backend:
  stage: backend
  <<: *backend_settings
  script:
    - cd backend
    - gradle build
  artifacts:
    paths:
      - backend/build/libs/*.jar
  only:
    - ci-cd-yml-file-for-backend


setup_env_files:
  stage: frontend
  <<: *frontend_settings
  script:
    - echo "$DOTENV_DEV" > dotenv_dev
    - echo "$DOTENV_PROD" > dotenv_prod
  only:
    - ci-cd-yml-file-for-backend

build_web_frontend_dev:
  stage: frontend
  <<: *frontend_settings
  script:
    - flutter pub run build_runner build
    - flutter build web -t lib/main_dev.dart
    - ls -l ./build/web
  dependencies:
    - setup_env_files
  artifacts:
    paths:
      - frontend/build/web
  only:
    - ci-cd-yml-file-for-backend

build_web_frontend_prod:
  stage: frontend
  <<: *frontend_settings
  script:
    - flutter pub run build_runner build
    - flutter build web -t lib/main_prod.dart
  dependencies:
    - setup_env_files
  artifacts:
    paths:
      - frontend/build/web
  only:
    - ci-cd-yml-file-for-backend

build_android_app_dev:
  stage: frontend
  <<: *frontend_settings
  script:
    - flutter pub run build_runner build
    - flutter build apk -t lib/main_dev.dart
  dependencies:
    - setup_env_files
  artifacts:
    paths:
      - frontend/build/app/outputs/flutter-apk
  only:
    - ci-cd-yml-file-for-backend

build_android_app_prod:
  stage: frontend
  <<: *frontend_settings
  script:
    - flutter pub run build_runner build
    - flutter build apk -t lib/main_prod.dart
  dependencies:
    - setup_env_files
  artifacts:
    paths:
      - frontend/build/app/outputs/flutter-apk
  only:
    - ci-cd-yml-file-for-backend
