before_script:
  - cd backend

stages:
  - test

test_backend:
  stage: test
  image: gradle:jdk17
  services:
    - name: mariadb:lts-jammy
      alias: mariadb

  variables:
    DATABASE_URL: jdbc:mariadb://mariadb:3306/playlist
    DATABASE_USERNAME: root
    DATABASE_PASSWORD: root_password
    DOCKER_ENV: true
  script:
    - gradle test
    - gradle build
  artifacts:
    paths:
      - backend/build/reports/tests/
      - backend/build/libs/*.jar
  only:
    - ci-cd-yml-file-for-backend