stages:
  - build
  - test

build_backend:
  stage: build
  script:
    - docker-compose -f docker-compose.ci.yml build
  artifacts:
    paths:
      - backend/build/libs/*.jar
  only:
    - ci-cd-yml-file-for-backend

test_backend:
  stage: test
  script:
    - docker-compose -f docker-compose.ci.yml run backend-test
  only:
    - ci-cd-yml-file-for-backend
