stages:
  - setup
  - test

install_mariadb:
  stage: setup
  script:
    - sudo apt update
    - sudo apt install mariadb-server
    - echo "12345678" | echo "n" | sudo mysql_secure_installation
    - echo "12345678" | sudo mysql -u root -p
    - MariaDB [(none)]> CREATE DATABASE IF NOT EXISTS playlist;
  artifacts:
    paths:
      - /var/lib/mysql
  only:
    - ci-cd-yml-file-for-backend