FROM mariadb:lts-jammy

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password
ENV MYSQL_DATABASE=playlist

# Expose the default MySQL port
EXPOSE 3306